version : '3.7'

services:
  web:
    image: nginx
    volumes:
      - ./conf:/etc/nginx/templates
    ports:
      - "9000:80"
    environment:
      - NGINX_PORT=80
    networks:
      - public

  rabbit:
    image: rabbitmq
    networks:
      - private
    ports:
      - "5672:5672"

  redis:
    image: redis:alpine
    restart: always
    networks:
      - private
    ports:
      - "6379:6379"

  gateway:
    image: node
    command: sh -c "/code/build.sh"
    volumes:
      - ./gateway:/code
    ports:
      - 8080:8080
    secrets:
      - db-pass
      - db-user
    environment:
      - AMQP_HOST=rabbit
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_PASS=/run/secrets/db-pass
      - DB_USER=/run/secrets/db-user
    depends_on:
      - db
      - redis
      - rabbit
    networks:
      - private
      - public

  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    deploy:
      replicas: 1
    secrets: 
      - db-pass
      - db-user
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-pass
    volumes:
      - ./gateway/queries:/docker-entrypoint-initdb.d
    networks:
      - private

secrets:
  db-pass: 
    file: secrets/db-pass.secret
  db-user: 
    file: secrets/db-user.secret

networks:
  private:
  public: