version : '3.7'

services:
  web:
    image: nginx
    volumes:
      - ./conf:/etc/nginx/templates
    ports:
      - "9000:80"
    environment:
      - NGINX_PORT=80
    networks:
      - public

  backend:
    image: alpine  
    command: sh -c "/code/build.sh"
    volumes:
      - ./:/code
    ports:
      - 8080:8080
    secrets:
      - db-pass
      - db-user
    environment:
      - DB_HOST=db
      - DB_PASS=/run/secrets/db-pass
      - DB_USER=/run/secrets/db-user
    depends_on:
      - db
    networks:
      - private
      - public

  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    deploy:
      replicas: 1
    secrets: 
      - db-pass
      - db-user
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-pass
    volumes:
      - ./queries:/docker-entrypoint-initdb.d
    networks:
      - private

secrets:
  db-pass: 
    file: secrets/db-pass.secret
  db-user: 
    file: secrets/db-user.secret

networks:
  private:
  public: